Repository spacemeshos/svm, pull requests merged in 2021-07, with the labels that each got.

#258 Unroll ergonomics
  Cargo.lock
  crates/abi/decoder/Cargo.toml
  crates/abi/decoder/src/decoder.rs
  crates/abi/encoder/Cargo.toml
  crates/abi/encoder/src/lib.rs
  crates/abi/encoder/src/traits.rs
  crates/abi/encoder/src/types/address.rs
  crates/abi/encoder/src/types/amount.rs
  crates/abi/encoder/src/types/boolean.rs
  crates/abi/encoder/src/types/mod.rs
  crates/abi/encoder/src/types/num_i16.rs
  crates/abi/encoder/src/types/num_i32.rs
  crates/abi/encoder/src/types/num_i64.rs
  crates/abi/encoder/src/types/num_i8.rs
  crates/abi/encoder/src/types/numeric.rs
  crates/abi/encoder/src/types/option.rs
  crates/abi/encoder/src/types/small_array.rs
  crates/abi/encoder/src/types/unit.rs
  crates/sdk/std/src/panic.rs
  crates/sdk/types/src/blob.rs
Labels: enhancement, svm, v0.3

#261 Removing obsolete FFI code from `svm-storage`
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/lib.rs
  crates/storage/src/kv/ffi.rs
  crates/storage/src/kv/mock/ffi.rs
  crates/storage/src/kv/mock/mod.rs
  crates/storage/src/kv/mod.rs
Labels: svm, svm-c-api, svm-core, v0.3

#262 `svm-storage` - removing the only left `unsafe`
  crates/storage/src/app/raw.rs
  crates/types/src/transaction/mod.rs
Labels: svm, svm-core, v0.3

#268 Only native host functions
  crates/runtime/Cargo.toml
  crates/runtime/src/context.rs
  crates/runtime/src/env/memory/app_store.rs
  crates/runtime/src/env/mod.rs
  crates/runtime/src/env/traits/store.rs
  crates/runtime/src/error/mod.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/runtime/config.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/testing.rs
  crates/runtime/src/vmcalls/mod.rs
  crates/runtime/tests/vmcalls_tests.rs
Labels: go-svm, svm, svm-c-api, svm-core, v0.3

#263 Rust-specific style-related quality of life improvements
  crates/runtime/src/runtime/config.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/ptr.rs
Labels: documentation, enhancement, svm, v0.3

#276 Moving from `App` to `Account` terminology - Part 2
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/api/wasm/receipt.rs
  crates/codec/src/receipt/spawn_app.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/tests/runtime_tests.rs
  crates/types/src/lib.rs
  crates/types/src/receipt/mod.rs
  crates/types/src/receipt/spawn_app.rs
Labels: AA, svm, v0.3

#275 Nuke `svm-common` and replaces it with `hex`
  Cargo.lock
  Cargo.toml
  crates/codec/Cargo.toml
  crates/codec/src/api/json/mod.rs
  crates/common/Cargo.lock
  crates/common/Cargo.toml
  crates/common/README.md
  crates/common/src/fmt.rs
  crates/common/src/lib.rs
  crates/runtime/Cargo.toml
  crates/storage/Cargo.toml
  crates/storage/src/kv/mock/fake.rs
  crates/types/Cargo.toml
  crates/types/src/address.rs
  crates/types/src/macros.rs
  src/lib.rs
Labels: svm, v0.3

#282 Moving from `App` to `Account` terminology - Part 4
  crates/codec/src/api/builder/app_builder.rs
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/api/json/spawn_app.rs
  crates/codec/src/app.rs
  crates/codec/src/receipt/error.rs
  crates/codec/src/receipt/exec_app.rs
  crates/runtime/src/env/ext.rs
  crates/runtime/src/env/mod.rs
  crates/runtime/src/runtime/default.rs
  crates/types/src/error.rs
  crates/types/src/lib.rs
  crates/types/src/receipt/mod.rs
  crates/types/src/receipt/spawn.rs
  crates/types/src/receipt/spawn_app.rs
  crates/types/src/spawn_account.rs
Labels: AA, svm, v0.3

#283 Moving from `App` to `Account` terminology - Part 5
  crates/codec/src/api/builder/tx_builder.rs
  crates/codec/src/api/json/exec_app.rs
  crates/codec/src/api/json/mod.rs
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/api/json/spawn.rs
  crates/codec/src/receipt/exec_app.rs
  crates/codec/src/transaction.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/mod.rs
  crates/types/src/account.rs
  crates/types/src/lib.rs
  crates/types/src/receipt/execute.rs
  crates/types/src/receipt/mod.rs
  crates/types/src/receipt/spawn.rs
  crates/types/src/transaction/mod.rs
Labels: AA, svm, v0.3

#284 Moving from `App` to `Account` terminology - Part 6
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/receipt/deploy_template.rs
  crates/codec/src/receipt/mod.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/tests/runtime_tests.rs
  crates/types/src/lib.rs
  crates/types/src/receipt/deploy_template.rs
  crates/types/src/receipt/mod.rs
Labels: AA, svm, v0.3

#285 Moving from `App` to `Account` terminology - Part 7
  crates/codec/src/api/builder/call.rs
  crates/codec/src/api/builder/deploy.rs
  crates/codec/src/api/builder/mod.rs
  crates/codec/src/api/builder/spawn.rs
  crates/codec/src/api/json/call.rs
  crates/codec/src/api/json/deploy.rs
  crates/codec/src/api/json/mod.rs
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/api/json/spawn.rs
  crates/codec/src/api/mod.rs
  crates/codec/src/api/wasm/call.rs
  crates/codec/src/api/wasm/deploy.rs
  crates/codec/src/api/wasm/mod.rs
  crates/codec/src/api/wasm/receipt.rs
  crates/codec/src/api/wasm/spawn.rs
  crates/codec/src/call.rs
  crates/codec/src/ext.rs
  crates/codec/src/field.rs
  crates/codec/src/lib.rs
  crates/codec/src/receipt/call.rs
  crates/codec/src/receipt/deploy.rs
  crates/codec/src/receipt/gas.rs
  crates/codec/src/receipt/logs.rs
  crates/codec/src/receipt/mod.rs
  crates/codec/src/receipt/spawn.rs
  crates/codec/src/spawn.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/src/env/ext.rs
  crates/runtime/src/env/mod.rs
  crates/runtime/src/testing.rs
  crates/runtime/tests/runtime_tests.rs
  crates/types/src/receipt/mod.rs
  crates/types/src/receipt/spawn.rs
Labels: AA, svm, v0.3

#286 Moving from `App` to `Account` terminology - Part 8
  crates/codec/examples/test.js
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/api/json/spawn.rs
  crates/codec/src/lib.rs
  crates/codec/src/receipt/call.rs
  crates/codec/src/receipt/error.rs
  crates/codec/src/receipt/mod.rs
  crates/codec/src/receipt/spawn.rs
  crates/runtime-ffi/src/api.rs
Labels: AA, svm, v0.3

#287 Moving from `App` to `Account` terminology - Part 9
  crates/runtime/src/context.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/storage.rs
  crates/runtime/src/testing.rs
  crates/storage/src/account/kv.rs
  crates/storage/src/account/mod.rs
  crates/storage/src/account/raw.rs
  crates/storage/src/kv/mock/fake.rs
  crates/storage/src/kv/mod.rs
  crates/storage/src/kv/traits.rs
  crates/storage/src/lib.rs
  crates/storage/src/testing.rs
  crates/storage/tests/account_storage_tests.rs
  crates/storage/tests/app_storage_tests.rs
Labels: AA, svm, v0.3

#288 Moving from `App` to `Account` terminology - Part 10
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/receipt/deploy.rs
  crates/codec/src/receipt/mod.rs
  crates/gas/src/lib.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/src/context.rs
  crates/runtime/src/env/default/address_compute.rs
  crates/runtime/src/env/default/memory.rs
  crates/runtime/src/env/default/mod.rs
  crates/runtime/src/env/default/serialize.rs
  crates/runtime/src/env/ext.rs
  crates/runtime/src/env/memory/account_store.rs
  crates/runtime/src/env/memory/app_store.rs
  crates/runtime/src/env/memory/mod.rs
  crates/runtime/src/env/mod.rs
  crates/runtime/src/env/rocksdb/account_store.rs
  crates/runtime/src/env/rocksdb/app_store.rs
  crates/runtime/src/env/rocksdb/mod.rs
  crates/runtime/src/env/traits/mod.rs
  crates/runtime/src/env/traits/serialize.rs
  crates/runtime/src/env/traits/store.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/runtime/call.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/src/storage_builder.rs
  crates/runtime/src/testing.rs
  crates/runtime/tests/runtime_tests.rs
  crates/runtime/tests/vmcalls_tests.rs
  crates/runtime/tests/wasm/runtime_call.wast
  crates/runtime/tests/wasm/runtime_spawn.wast
Labels: AA, svm, v0.3

#292 Moving from `App` to `Account` terminology - Part 11
  crates/gas/src/gas.rs
  crates/gas/src/lib.rs
  crates/runtime/src/env/default/rocksdb.rs
  crates/runtime/src/env/mod.rs
  crates/runtime/src/env/rocksdb/account_store.rs
  crates/runtime/src/env/rocksdb/template_store.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/runtime/rocksdb.rs
Labels: AA, svm, v0.3

#296 Moving from `App` to `Account` terminology - Part 13
  crates/codec/src/api/json/deploy.rs
  crates/codec/src/section/sections/data.rs
  crates/layout/src/builder.rs
  crates/layout/src/fixed.rs
  crates/layout/src/lib.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/sdk-tests/tests/ctor.rs
Labels: AA, svm, v0.3

#297 Moving from `App` to `Account` terminology - Part 14
  crates/runtime-ffi/tests/wasm/counter.wasm
  crates/runtime-ffi/tests/wasm/counter/Cargo.lock
  crates/runtime-ffi/tests/wasm/counter/src/lib.rs
  crates/runtime-ffi/tests/wasm/failure/Cargo.lock
  crates/runtime-ffi/tests/wasm/failure/src/lib.rs
  crates/runtime/tests/wasm/calldata/Cargo.lock
  crates/runtime/tests/wasm/calldata/src/lib.rs
  crates/runtime/tests/wasm/runtime_calldata.wasm
Labels: AA, svm, v0.3

#289 Create tracking issues for most TODOs in the code
  crates/gas/src/lib.rs
  crates/layout/src/lib.rs
  crates/sdk/macros/src/template.rs
  crates/types/src/template/api.rs
  crates/types/src/template/mod.rs
Labels: documentation, svm, v0.3

#298 Use a `PriceResolver` registry with dynamic dispatch
  crates/cli/src/main.rs
  crates/gas/src/pricing/cfg.rs
  crates/gas/src/pricing/mod.rs
  crates/gas/tests/helpers.rs
  crates/gas/tests/pricing.rs
  crates/runtime/src/env/default/memory.rs
  crates/runtime/src/env/mod.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/price_resolver_registry.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/testing.rs
Labels: svm, v0.3

#300 Revamp the `svm-cli` crate
  Cargo.lock
  Cargo.toml
  crates/cli/Cargo.toml
  crates/cli/src/main.rs
Labels: svm, v0.3

#299 Naive template memoization
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/testing.rs
Labels: svm, v0.3

#305 Some cleaning
  crates/runtime/src/context.rs
  crates/runtime/src/env/ext.rs
  crates/runtime/src/env/mod.rs
  crates/runtime/src/env/traits/compute_address.rs
  crates/runtime/src/env/traits/mod.rs
  crates/runtime/src/env/traits/serialize.rs
  crates/runtime/src/env/traits/store.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/price_resolver_registry.rs
  crates/runtime/src/runtime/call.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/src/testing.rs
  crates/runtime/tests/vmcalls_tests.rs
  crates/types/src/receipt/deploy_template.rs
  crates/types/src/receipt/spawn.rs
  crates/types/src/transaction/mod.rs
Labels: small, svm, v0.3

#306 Runtime `Context` rename
  crates/runtime/src/env/mod.rs
  crates/runtime/src/func_env.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/vmcalls/alloc.rs
  crates/runtime/src/vmcalls/calldata.rs
  crates/runtime/src/vmcalls/logs.rs
  crates/runtime/src/vmcalls/mod.rs
  crates/runtime/src/vmcalls/returndata.rs
  crates/runtime/src/vmcalls/storage.rs
  crates/runtime/tests/vmcalls_tests.rs
Labels: AA, svm, svm-core, v0.3

#310 codec - ASCII Charts slight modifications.
  crates/codec/src/call.rs
  crates/codec/src/spawn.rs
  crates/codec/src/template.rs
Labels: svm

#308 `svm-cli` `Transaction` crafting: `spawn`
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/examples/call.json
  crates/cli/examples/deploy.json
  crates/cli/examples/spawn.json
  crates/cli/src/clap_app.rs
  crates/cli/src/main.rs
  crates/cli/src/subcmd_tx.rs
  crates/cli/src/subcmd_validate.rs
  crates/codec/Cargo.toml
Labels: enhancement, svm, v0.3

#311 Transaction `Envelope` and `Context`
  crates/abi/decoder/src/lib.rs
  crates/codec/src/api/builder/call.rs
  crates/codec/src/api/builder/mod.rs
  crates/codec/src/api/json/spawn.rs
  crates/codec/src/context.rs
  crates/codec/src/envelope.rs
  crates/codec/src/lib.rs
  crates/codec/src/receipt/deploy.rs
  crates/codec/src/spawn.rs
  crates/codec/src/template.rs
  crates/ffi/src/byte_array.rs
  crates/ffi/src/lib.rs
  crates/ffi/src/macros.rs
  crates/ffi/src/tracking/interning.rs
  crates/layout/src/lib.rs
  crates/query/src/lib.rs
  crates/query/src/query.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/error.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/src/env/default/address_compute.rs
  crates/runtime/src/env/default/memory.rs
  crates/runtime/src/env/default/mod.rs
  crates/runtime/src/env/rocksdb/account_store.rs
  crates/runtime/src/runtime/call.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/src/runtime/ptr.rs
  crates/runtime/src/runtime/rocksdb.rs
  crates/runtime/src/storage.rs
  crates/runtime/src/testing.rs
  crates/runtime/tests/runtime_tests.rs
  crates/runtime/tests/vmcalls_tests.rs
  crates/runtime/tests/wasm/load160_store160.wast
  crates/runtime/tests/wasm/runtime_call.wast
  crates/runtime/tests/wasm/runtime_spawn.wast
  crates/sdk/alloc/src/lib.rs
  crates/sdk/std/src/lib.rs
  crates/sdk/std/src/log.rs
  crates/storage/src/lib.rs
  crates/types/src/address.rs
  crates/types/src/lib.rs
  crates/types/src/receipt/call.rs
  crates/types/src/receipt/deploy.rs
  crates/types/src/receipt/mod.rs
  crates/types/src/spawn_account.rs
  crates/types/src/transaction/context.rs
  crates/types/src/transaction/envelope.rs
  crates/types/src/transaction/layer.rs
  crates/types/src/transaction/mod.rs
Labels: AA, go-svm, svm, svm-c-api, svm-core, v0.3

#315 Replace macros with functions within svm-storage
  crates/storage/tests/account_storage_tests.rs
Labels: small, svm, v0.3

#312 Refactoring of `svm_codec::api::json` with Serde
  Cargo.lock
  crates/cli/src/subcmd_tx.rs
  crates/codec/Cargo.toml
  crates/codec/examples/test.js
  crates/codec/src/api/json/call.rs
  crates/codec/src/api/json/calldata.rs
  crates/codec/src/api/json/deploy.rs
  crates/codec/src/api/json/error.rs
  crates/codec/src/api/json/mod.rs
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/api/json/serde_types.rs
  crates/codec/src/api/json/spawn.rs
  crates/codec/src/api/wasm/call.rs
  crates/codec/src/api/wasm/calldata.rs
  crates/codec/src/api/wasm/deploy.rs
  crates/codec/src/api/wasm/error.rs
  crates/codec/src/api/wasm/mod.rs
  crates/codec/src/api/wasm/receipt.rs
  crates/codec/src/api/wasm/spawn.rs
  crates/sdk/types/src/value.rs
Labels: enhancement, medium, svm, v0.3

#317 Catch panics within critical FFI calls
  crates/runtime-ffi/src/api.rs
Labels: svm, svm-c-api, v0.3

#316 Refactoring for SDK Auto-generated Metadata
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/main.rs
  crates/cli/src/sections.rs
  crates/codec/src/api/builder/deploy.rs
  crates/codec/src/lib.rs
  crates/codec/src/section/decode.rs
  crates/codec/src/section/encode.rs
  crates/codec/src/section/preview.rs
  crates/runtime/tests/wasm/calldata/Cargo.lock
  crates/runtime/tests/wasm/calldata/Cargo.toml
  crates/runtime/tests/wasm/calldata/build.sh
  crates/runtime/tests/wasm/calldata/src/lib.rs
  crates/runtime/tests/wasm/runtime_calldata.wasm
  crates/sdk-tests/Cargo.toml
  crates/sdk-tests/tests/meta.rs
  crates/sdk-tests/tests/meta/ctor_fundable_meta.rs
  crates/sdk-tests/tests/meta/ctor_meta.rs
  crates/sdk-tests/tests/meta/ctor_with_doc.rs
  crates/sdk-tests/tests/meta/endpoint_fundable_meta.rs
  crates/sdk-tests/tests/meta/endpoint_with_doc.rs
  crates/sdk-tests/tests/meta/endpoint_with_params_array_meta.rs
  crates/sdk-tests/tests/meta/endpoint_with_params_meta.rs
  crates/sdk-tests/tests/meta/endpoint_with_returns_path_meta.rs
  crates/sdk-tests/tests/meta/endpoint_with_returns_tuple_meta.rs
  crates/sdk-tests/tests/meta/storage_meta.rs
  crates/sdk-tests/tests/schema.rs
  crates/sdk/Cargo.toml
  crates/sdk/macros/Cargo.toml
  crates/sdk/macros/src/function/attr.rs
  crates/sdk/macros/src/function/ctor.rs
  crates/sdk/macros/src/function/endpoint.rs
  crates/sdk/macros/src/function/fundable_hook.rs
  crates/sdk/macros/src/function/mod.rs
  crates/sdk/macros/src/json.rs
  crates/sdk/macros/src/lib.rs
  crates/sdk/macros/src/meta.rs
  crates/sdk/macros/src/struct/attr.rs
  crates/sdk/macros/src/struct/mod.rs
  crates/sdk/macros/src/struct/storage.rs
  crates/sdk/macros/src/struct/var.rs
  crates/sdk/macros/src/template.rs
  crates/sdk/macros/src/type.rs
  crates/types/src/lib.rs
  crates/types/src/template/api.rs
  crates/types/src/template/code.rs
  crates/types/src/template/ctors.rs
  crates/types/src/template/data.rs
  crates/types/src/template/deploy.rs
  crates/types/src/template/header.rs
  crates/types/src/template/mod.rs
  crates/types/src/template/schema.rs
  crates/types/src/template/section.rs
Labels: enhancement, go-svm, svm, v0.3

#318 Craft Deploy transactions from the CLI
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/examples/craft-deploy/Cargo.lock
  crates/cli/examples/craft-deploy/Cargo.toml
  crates/cli/examples/craft-deploy/build.sh
  crates/cli/examples/craft-deploy/src/lib.rs
  crates/cli/examples/tx-call.json
  crates/cli/examples/tx-deploy.json
  crates/cli/examples/tx-spawn.json
  crates/cli/src/clap_app.rs
  crates/cli/src/main.rs
  crates/cli/src/sections.rs
  crates/cli/src/subcmd_craft_deploy/meta.rs
  crates/cli/src/subcmd_craft_deploy/mod.rs
  crates/cli/src/subcmd_tx.rs
  crates/sdk/types/src/value.rs
Labels: svm, v0.3

#319 Removing `AddressOf<..>`
  crates/codec/src/api/builder/call.rs
  crates/codec/src/api/builder/spawn.rs
  crates/codec/src/api/json/mod.rs
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/api/json/serde_types.rs
  crates/codec/src/api/json/spawn.rs
  crates/codec/src/call.rs
  crates/codec/src/ext.rs
  crates/codec/src/field.rs
  crates/codec/src/receipt/call.rs
  crates/codec/src/receipt/deploy.rs
  crates/codec/src/receipt/error.rs
  crates/codec/src/receipt/spawn.rs
  crates/codec/src/section/sections/deploy.rs
  crates/codec/src/spawn.rs
  crates/codec/src/template.rs
  crates/runtime/src/env/default/address_compute.rs
  crates/runtime/src/env/default/serialize.rs
  crates/runtime/src/env/ext.rs
  crates/runtime/src/env/memory/account_store.rs
  crates/runtime/src/env/mod.rs
  crates/runtime/src/env/traits/store.rs
  crates/runtime/src/func_env.rs
  crates/runtime/src/runtime/call.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/storage.rs
  crates/runtime/src/testing.rs
  crates/runtime/tests/runtime_tests.rs
  crates/runtime/tests/vmcalls_tests.rs
  crates/types/src/account.rs
  crates/types/src/address.rs
  crates/types/src/address_of.rs
  crates/types/src/error.rs
  crates/types/src/lib.rs
  crates/types/src/receipt/spawn.rs
  crates/types/src/template/deploy.rs
  crates/types/src/transaction/mod.rs
Labels: svm, svm-core, v0.3

#320 Migrating `svm-ffi` into `svm-runtime-ffi` crate
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/ffi/Cargo.toml
  crates/ffi/build.rs
  crates/ffi/src/lib.rs
  crates/runtime-ffi/Cargo.toml
  crates/runtime-ffi/build.rs
  crates/runtime-ffi/src/address.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/byte_array.rs
  crates/runtime-ffi/src/error.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime-ffi/src/macros.rs
  crates/runtime-ffi/src/ref.rs
  crates/runtime-ffi/src/state.rs
  crates/runtime-ffi/src/tracking/interning.rs
  crates/runtime-ffi/src/tracking/mod.rs
  crates/runtime-ffi/src/tracking/snapshot.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/lib.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/src/runtime/ptr.rs
  src/lib.rs
Labels: svm, svm-c-api, v0.3

#321 Singlepass feature flag
  Cargo.lock
  Cargo.toml
  crates/runtime-ffi/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/wasm_store.rs
Labels: svm, v0.3

#322 Rename crates authors
  Cargo.lock
  Cargo.toml
  crates/abi/decoder/Cargo.toml
  crates/abi/encoder/Cargo.toml
  crates/abi/layout/Cargo.toml
  crates/abi/tests/Cargo.toml
  crates/cli/src/main.rs
  crates/codec/Cargo.toml
  crates/codec/examples/package.json
  crates/gas/Cargo.toml
  crates/hash/Cargo.toml
  crates/kv/Cargo.toml
  crates/layout/Cargo.toml
  crates/program/Cargo.toml
  crates/query/Cargo.toml
  crates/runtime-ffi/Cargo.toml
  crates/runtime-ffi/tests/wasm/counter/Cargo.toml
  crates/runtime-ffi/tests/wasm/failure/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/tests/wasm/calldata/Cargo.toml
  crates/sdk-tests/Cargo.toml
  crates/sdk/Cargo.toml
  crates/sdk/alloc/Cargo.toml
  crates/sdk/host/Cargo.toml
  crates/sdk/macros/Cargo.toml
  crates/sdk/std/Cargo.toml
  crates/sdk/storage/Cargo.toml
  crates/sdk/types/Cargo.toml
  crates/storage/Cargo.toml
  crates/types/Cargo.toml
Labels: documentation, svm, v0.3

#323 svm-runtime: Injecting the `Envelope` and `Context` into `FuncEnv`
  crates/codec/src/section/preview.rs
  crates/runtime/src/func_env.rs
  crates/runtime/src/runtime/call.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/failure.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/src/vmcalls/alloc.rs
  crates/runtime/src/vmcalls/calldata.rs
  crates/runtime/src/vmcalls/logs.rs
  crates/runtime/src/vmcalls/storage.rs
  crates/runtime/tests/vmcalls_tests.rs
  crates/types/src/transaction/context.rs
  crates/types/src/transaction/envelope.rs
Labels: svm, v0.3

#324 `svm-runtime-ffi` tests restoration
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/context.rs
  crates/codec/src/envelope.rs
  crates/codec/src/ext.rs
  crates/codec/src/receipt/error.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/byte_array.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime-ffi/tests/wasm/counter.wasm
  crates/runtime-ffi/tests/wasm/counter/Cargo.lock
  crates/runtime-ffi/tests/wasm/counter/src/lib.rs
  crates/runtime-ffi/tests/wasm/failure.wasm
  crates/runtime-ffi/tests/wasm/failure/Cargo.lock
  crates/runtime-ffi/tests/wasm/failure/src/lib.rs
  crates/runtime/src/runtime/default.rs
  crates/types/src/error.rs
Labels: svm, svm-c-api, v0.3
