Repository spacemeshos/svm, pull requests merged in 2021-12, with the labels that each got.

#428 Wasmer update to v2.1.0
  .github/workflows/ci.yml
  .guppy/hakari.toml
  Cargo.lock
  crates/runtime-ffi/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/wasm_store.rs
  crates/svm-workspace-hack/Cargo.toml
  crates/svm/Cargo.toml
Labels: dependencies, svm

#430 Touched accounts
  crates/codec/src/api/json/mod.rs
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/receipt/call.rs
  crates/codec/src/receipt/mod.rs
  crates/codec/src/receipt/spawn.rs
  crates/codec/src/receipt/touched_accounts.rs
  crates/runtime/src/func_env.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/runtime/function.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/src/runtime/runtime.rs
  crates/runtime/src/vmcalls/transfer.rs
  crates/runtime/tests/runtime_tests.rs
  crates/state/src/account_storage.rs
  crates/types/src/receipt/call.rs
  crates/types/src/receipt/spawn.rs
Labels: svm-core, v0.3, svm

#432 Improve C API initialization patterns
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/config.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime-ffi/tests/api_tests.rs
Labels: svm-c-api

#433 Additional testing for Touched-Accounts and update codec documentation
  crates/codec/src/receipt/call.rs
  crates/codec/src/receipt/spawn.rs
Labels: small, svm

#435 Runtime refactoring
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/receipt/error.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/src/func_env.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/price_registry.rs
  crates/runtime/src/runtime/call.rs
  crates/runtime/src/runtime/gas_tank.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/src/runtime/price_cache.rs
  crates/runtime/src/runtime/runtime.rs
  crates/runtime/src/testing.rs
  crates/runtime/src/vmcalls/mod.rs
  crates/runtime/tests/runtime_tests.rs
  crates/runtime/tests/vmcalls_tests.rs
  crates/state/src/account_storage.rs
  crates/types/src/error.rs
  crates/types/src/template/mod.rs
  crates/types/src/template/section.rs
Labels: refactoring
