Repository spacemeshos/svm, pull requests merged in 2021-08, with the labels that each got.

#331 Adding `returndata byte-size` field to Receipts
  crates/codec/src/call.rs
  crates/codec/src/receipt/call.rs
  crates/codec/src/receipt/deploy.rs
  crates/codec/src/receipt/error.rs
  crates/codec/src/receipt/mod.rs
  crates/codec/src/receipt/returndata.rs
  crates/codec/src/receipt/spawn.rs
Labels: svm, v0.3

#332 AA `verify`
  crates/abi/decoder/src/calldata.rs
  crates/codec/build.sh
  crates/codec/examples/test.js
  crates/codec/src/api/builder/call.rs
  crates/codec/src/api/json/call.rs
  crates/codec/src/api/json/inputdata.rs
  crates/codec/src/api/json/mod.rs
  crates/codec/src/api/json/spawn.rs
  crates/codec/src/api/wasm/call.rs
  crates/codec/src/api/wasm/inputdata.rs
  crates/codec/src/api/wasm/mod.rs
  crates/codec/src/api/wasm/spawn.rs
  crates/codec/src/call.rs
  crates/codec/src/calldata.rs
  crates/codec/src/field.rs
  crates/codec/src/inputdata.rs
  crates/codec/src/lib.rs
  crates/codec/src/spawn.rs
  crates/program/src/error.rs
  crates/program/src/program.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime/src/error.rs
  crates/runtime/src/func_env.rs
  crates/runtime/src/runtime/call.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/tests/runtime_tests.rs
  crates/runtime/tests/vmcalls_tests.rs
  crates/runtime/tests/wasm/calldata/Cargo.lock
  crates/runtime/tests/wasm/missing_svm_alloc.wast
  crates/runtime/tests/wasm/missing_svm_verify.wast
  crates/runtime/tests/wasm/runtime_calldata.wasm
  crates/runtime/tests/wasm/svm_alloc_invalid_sig.wast
  crates/runtime/tests/wasm/svm_verify_invalid_sig.wast
  crates/sdk/macros/Cargo.toml
  crates/sdk/macros/src/template.rs
  crates/sdk/types/Cargo.toml
  crates/types/src/transaction/mod.rs
Labels: v0.3, svm, AA

#334 Protected Mode for `verify`
  crates/kv/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/func_env.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/runtime/call.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/vmcalls/logs.rs
  crates/runtime/src/vmcalls/storage.rs
  crates/runtime/tests/vmcalls_tests.rs
Labels: svm-core, v0.3, svm, AA

#335 SVM SDK String
  Cargo.lock
  Cargo.toml
  crates/abi/decoder/Cargo.toml
  crates/codec/src/api/json/mod.rs
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/field.rs
  crates/codec/src/receipt/call.rs
  crates/codec/src/receipt/error.rs
  crates/codec/src/receipt/logs.rs
  crates/codec/src/receipt/spawn.rs
  crates/runtime/src/vmcalls/logs.rs
  crates/runtime/tests/vmcalls_tests.rs
  crates/runtime/tests/wasm/log.wast
  crates/sdk/std/Cargo.toml
  crates/sdk/std/src/ensure.rs
  crates/sdk/std/src/lib.rs
  crates/sdk/std/src/log.rs
  crates/sdk/std/src/option.rs
  crates/sdk/std/src/result.rs
  crates/sdk/std/src/string/builder.rs
  crates/sdk/std/src/string/digit.rs
  crates/sdk/std/src/string/mod.rs
  crates/sdk/std/src/string/traits.rs
  crates/sdk/std/src/vec.rs
  crates/sdk/types/Cargo.toml
  crates/sdk/types/src/amount.rs
  crates/sdk/types/src/blob.rs
  crates/sdk/types/src/layer_id.rs
  crates/sdk/types/src/lib.rs
  crates/sdk/types/src/value.rs
  crates/types/src/receipt/log.rs
Labels: v0.3, svm, sdk

#338 A few leftovers from the SVM SDK PR
  crates/runtime/tests/wasm/log.wast
  crates/sdk/std/src/log.rs
  crates/sdk/std/src/string/mod.rs
  crates/sdk/types/Cargo.toml
Labels: v0.3, svm

#339 Small documentation improvements
  LICENSE
  crates/cli/src/main.rs
  crates/hash/src/lib.rs
  src/lib.rs
Labels: documentation, rust, v0.3, svm

#333 Global State: versioned KV store with root signature calculation
  Cargo.lock
  Cargo.toml
  crates/hash/Cargo.toml
  crates/hash/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/env/default/address_compute.rs
  crates/runtime/src/env/default/hasher.rs
  crates/state/Cargo.toml
  crates/state/src/error.rs
  crates/state/src/lib.rs
  crates/state/src/resources/schema.sql
  crates/storage/src/account/kv.rs
  crates/storage/src/kv/mock/fake.rs
Labels: svm-core, v0.3, svm

#342 Replace `Runtime` locking mechanisms with thread-safe alternatives
  crates/runtime/src/func_env.rs
  crates/runtime/src/testing.rs
  crates/storage/src/account/kv.rs
  crates/storage/src/testing.rs
Labels: rust, v0.3, svm

#345 Adopt `thiserror` for `ParseError` and `#[derive(Debug)]`
  crates/codec/src/error.rs
Labels: enhancement, v0.3, svm

#346 Inline contents of some helper functions in `svm_codec`
  crates/codec/src/call.rs
  crates/codec/src/spawn.rs
Labels: v0.3, svm

#347 Always compile WASM APIs in `svm_codec`
  crates/codec/src/lib.rs
Labels: v0.3, svm

#348 Remove builder patterns in `svm_codec`
  crates/cli/src/subcmd_craft_deploy/mod.rs
  crates/codec/src/api/builder/call.rs
  crates/codec/src/api/builder/deploy.rs
  crates/codec/src/api/builder/mod.rs
  crates/codec/src/api/builder/spawn.rs
  crates/codec/src/api/json/deploy.rs
  crates/codec/src/api/mod.rs
  crates/codec/src/api/wasm/deploy.rs
  crates/codec/src/section/encode.rs
  crates/codec/src/template.rs
  crates/runtime/src/testing.rs
  crates/types/src/spawn_account.rs
  crates/types/src/template/mod.rs
Labels: v0.3, svm

#349 `Codec`: simplifying encoding and decoding with traits
  crates/codec/src/api/json/call.rs
  crates/codec/src/api/json/spawn.rs
  crates/codec/src/codec_impls.rs
  crates/codec/src/context.rs
  crates/codec/src/envelope.rs
  crates/codec/src/inputdata.rs
  crates/codec/src/lib.rs
  crates/codec/src/section/sections/deploy.rs
  crates/codec/src/version.rs
  crates/codec/src/wasm_ffi.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/src/env/mod.rs
  crates/runtime/src/testing.rs
Labels: enhancement, v0.3, svm

#350 `Codec`: simplifying encoding and decoding with traits (receipts)
  crates/codec/src/api/json/call.rs
  crates/codec/src/api/json/receipt.rs
  crates/codec/src/api/wasm/receipt.rs
  crates/codec/src/receipt/call.rs
  crates/codec/src/receipt/deploy.rs
  crates/codec/src/receipt/error.rs
  crates/codec/src/receipt/gas.rs
  crates/codec/src/receipt/logs.rs
  crates/codec/src/receipt/mod.rs
  crates/codec/src/receipt/returndata.rs
  crates/codec/src/receipt/spawn.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/byte_array.rs
  crates/runtime-ffi/tests/api_tests.rs
Labels: v0.3, svm

#351 Safer C APIs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/byte_array.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime-ffi/src/ref.rs
  crates/runtime-ffi/tests/api_tests.rs
Labels: svm-c-api, v0.3, svm

#352 Disallow broken intra-doc Cargo links
  .github/workflows/ci.yml
  crates/abi/decoder/src/lib.rs
  crates/abi/encoder/src/lib.rs
  crates/abi/layout/src/lib.rs
  crates/cli/src/main.rs
  crates/codec/src/lib.rs
  crates/gas/src/lib.rs
  crates/hash/src/lib.rs
  crates/kv/src/lib.rs
  crates/layout/src/lib.rs
  crates/program/src/lib.rs
  crates/query/src/lib.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime/src/lib.rs
  crates/sdk/alloc/src/lib.rs
  crates/sdk/host/src/lib.rs
  crates/sdk/macros/src/lib.rs
  crates/sdk/std/src/lib.rs
  crates/sdk/std/src/option.rs
  crates/sdk/std/src/string/mod.rs
  crates/sdk/std/src/vec.rs
  crates/sdk/storage/src/lib.rs
  crates/state/src/lib.rs
  crates/storage/src/lib.rs
  crates/types/src/lib.rs
Labels: documentation, small, v0.3, svm

#354 Only compile svm-runtime-ffi in CI
  .github/workflows/ci.yml
Labels: svm-c-api, v0.3, svm

#364 Expose CLI builds as GitHub Actions artifactts
  .github/workflows/ci.yml
  Cargo.lock
  crates/cli/Cargo.toml
Labels: v0.3, svm
