Repository spacemeshos/svm, pull requests merged in 2021-09, with the labels that each got.

#357 Global State - Higher level APIS (Part 1)
  Cargo.lock
  crates/codec/src/ext.rs
  crates/codec/src/section/mod.rs
  crates/state/Cargo.toml
  crates/state/src/account_data.rs
  crates/state/src/account_storage.rs
  crates/state/src/error.rs
  crates/state/src/global_state.rs
  crates/state/src/lib.rs
  crates/state/src/storage.rs
Labels: critical, v0.3, svm

#366 `svm_state::AccountStorage`: phase out `svm-storage` and `svm-kv`
  Cargo.lock
  Cargo.toml
  crates/codec/src/codec.rs
  crates/kv/.gitignore
  crates/kv/Cargo.toml
  crates/kv/src/key.rs
  crates/kv/src/lib.rs
  crates/kv/src/memory.rs
  crates/kv/src/rocksdb/db.rs
  crates/kv/src/rocksdb/mod.rs
  crates/kv/src/traits.rs
  crates/kv/tests/asserts.rs
  crates/kv/tests/memory_kv_tests.rs
  crates/query/src/query.rs
  crates/runtime-ffi/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/func_env.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/rocksdb.rs
  crates/runtime/src/storage.rs
  crates/runtime/src/testing.rs
  crates/runtime/src/vmcalls/storage.rs
  crates/runtime/tests/vmcalls_tests.rs
  crates/state/Cargo.toml
  crates/state/src/account_data.rs
  crates/state/src/account_storage.rs
  crates/state/src/error.rs
  crates/state/src/global_state.rs
  crates/state/src/lib.rs
  crates/state/src/storage.rs
  crates/state/src/template_storage.rs
  crates/storage/Cargo.toml
  crates/storage/src/account/kv.rs
  crates/storage/src/account/mod.rs
  crates/storage/src/account/raw.rs
  crates/storage/src/kv/mock/fake.rs
  crates/storage/src/kv/mock/mod.rs
  crates/storage/src/kv/mod.rs
  crates/storage/src/kv/traits.rs
  crates/storage/src/lib.rs
  crates/storage/src/testing.rs
  crates/storage/tests/account_storage_tests.rs
  crates/types/src/transaction/layer.rs
  src/lib.rs
Labels: svm-core, v0.3, svm

#371 Better code reuse and making FFI simpler and more streamlined
  Cargo.lock
  Cargo.toml
  crates/codec/src/receipt/call.rs
  crates/codec/src/receipt/deploy.rs
  crates/codec/src/receipt/error.rs
  crates/codec/src/receipt/mod.rs
  crates/codec/src/receipt/spawn.rs
  crates/hash/src/lib.rs
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/byte_array.rs
  crates/runtime-ffi/src/error.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime-ffi/src/ref.rs
  crates/runtime-ffi/src/result.rs
  crates/runtime-ffi/src/tracking/interning.rs
  crates/runtime-ffi/src/tracking/mod.rs
  crates/runtime-ffi/src/tracking/snapshot.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/src/ext.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/failure.rs
  crates/runtime/src/runtime/mod.rs
  crates/svm/Cargo.toml
  crates/svm/src/lib.rs
  crates/types/src/error.rs
  crates/types/src/lib.rs
Labels: v0.3, svm

#381 Replace all usage of Actix with Tokio
  Cargo.lock
  crates/state/Cargo.toml
Labels: small, v0.3, svm

#382 Remove the `svm_abi_layout::layout` module
  crates/abi-decoder/src/decoder.rs
  crates/abi-encoder/src/types/address.rs
  crates/abi-encoder/src/types/boolean.rs
  crates/abi-encoder/src/types/numeric.rs
  crates/abi-encoder/src/types/option.rs
  crates/abi-encoder/src/types/unit.rs
  crates/abi-layout/src/lib.rs
Labels: v0.3, svm

#378 Self-healing -related FFI
  Cargo.lock
  crates/runtime-ffi/Cargo.toml
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/config.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime-ffi/src/result.rs
  crates/runtime-ffi/src/runtime_tracker.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/price_registry.rs
  crates/runtime/src/runtime/default.rs
  crates/runtime/src/runtime/mod.rs
  crates/sdk-std/src/lib.rs
  crates/sdk-std/src/vec.rs
  crates/sdk/src/lib.rs
  crates/state/src/storage.rs
  crates/types/Cargo.toml
  crates/types/src/error.rs
  tests/abi/Cargo.toml
Labels: svm-c-api, v0.3, svm

#380 Nuke RocksDB remnants as well as `default-memory`, `default-rocksdb`
  .github/workflows/ci.yml
  README.md
  crates/runtime-ffi/Cargo.toml
  crates/runtime-ffi/src/api.rs
  crates/runtime-ffi/src/lib.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/lib.rs
  crates/runtime/src/runtime/mod.rs
  crates/runtime/src/runtime/rocksdb.rs
  crates/runtime/src/testing.rs
  crates/svm/Cargo.toml
Labels: enhancement, v0.3, svm

#383 Simpler type signature of `svm_abi_encoder::Encoder` & reduce use of `unsafe`
  crates/abi-decoder/src/calldata.rs
  crates/abi-decoder/src/cursor.rs
  crates/abi-decoder/src/decoder.rs
  crates/abi-decoder/src/lib.rs
  crates/abi-encoder/src/traits.rs
  crates/abi-encoder/src/types/address.rs
  crates/abi-encoder/src/types/amount.rs
  crates/abi-encoder/src/types/boolean.rs
  crates/abi-encoder/src/types/mod.rs
  crates/abi-encoder/src/types/numeric.rs
  crates/abi-encoder/src/types/option.rs
  crates/abi-encoder/src/types/small_array.rs
  crates/abi-encoder/src/types/tuples.rs
  crates/abi-encoder/src/types/unit.rs
  crates/query/src/render.rs
  crates/sdk-host/src/mock.rs
  tests/sdk/src/lib.rs
Labels: v0.3, svm

#384 Simplify `FixedLayout`: builder pattern, iteration and representation
  crates/cli/src/subcmd_craft_deploy/meta.rs
  crates/cli/src/subcmd_craft_deploy/mod.rs
  crates/codec/src/api/json/deploy.rs
  crates/codec/src/section/sections/data.rs
  crates/codec/src/template.rs
  crates/layout/src/builder.rs
  crates/layout/src/fixed.rs
  crates/layout/src/lib.rs
  crates/layout/src/var.rs
  crates/runtime-ffi/tests/api_tests.rs
  crates/runtime/tests/runtime_tests.rs
  crates/runtime/tests/vmcalls_tests.rs
  crates/state/src/account_storage.rs
  crates/state/src/template_storage.rs
Labels: v0.3, svm

#386 Added the `nonce` field to the `Envelope`
  crates/codec/src/codec.rs
  crates/types/src/transaction/envelope.rs
Labels: svm-c-api, v0.3, svm
